apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movie-deployment
  labels:
    app: go-movie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-movie
  template:
    metadata:
      labels:
        app: go-movie
    spec:
      containers:
      - name: go-movie
        image: bishalr0y/go-movie-crud:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
      - name:  dockerhub-cred
